title: Site

tabs:

  content:
    label: Content
    icon: text
    sections:

      pages:
        headline: Pages
        type: pages
        create:
          - project
          - textpage
        image:
          query: page.images.filterBy('template', 'project').sortBy('sort').first
          conver: true

  settings:
    label: Settings
    icon: cog
    sections:

      logo:
        type: files
        template: logo
        empty: No logo yet
        max: 1
        sortable: false
        layout: cards
        size: tiny
        info: "{{ file.width }} x {{ file.height }}"
        image:
          cover: false
          back: white

      fields:
        type: fields
        fields:

          tagline:
            label: Tagline
            type: text
            help: >
              Tagline will be displayed in title tag next to your site name.
              (e.g. {{ site.title }} - Your Custom Tagline)

          description:
            label: Description
            type: textarea

          social:
            label: Social
            type: structure
            fields:
              name:
                label: Name
                type: text
              code:
                label: Code
                type: text
                help: Font Awesome Unicode code.
              url:
                label: Url
                type: url

          footer:
            label: Footer
            type: textarea
            buttons: false
            help: >
              This theme is completely free for both personal and commercial use,
              however any kind of attribution is appreciated.
