title: Site

sections:

  pages:
    headline: Pages
    type: pages
    create:
      - project
      - textpage
    image:
      query: page.images.filterBy('template', 'project').sortBy('sort').first
      conver: true
